ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
== Introducci칩n y Objetivos 游꾾

El proyecto de WIQ 04D es un proyecto desarrollado en la asignatura Arquitectura del Software. Consiste en la creaci칩n de una aplicaci칩n web al estilo "Saber y Ganar". Es decir, es un juego de preguntas de cultura general generadas de forma autom치tica con ayuda de Wikidata, una base de conocimiento que puede ser le칤da y editada por humanos y por m치quinas.

Los desarrolladores de la aplicaci칩n son Zohaib Akhtar Kausar, Yago Navajas Gonz치lez y Santiago L칩pez Laso.

=== Requisitos Funcionales

****
* Los usuarios deber치n iniciar sesi칩n en la p치gina; esto servir치 para tener registro de una serie de par치metros, como puede ser las veces que se ha jugado. 
* Se podr치n responder preguntas autogeneradas y se mostrar치 si han acertado o fallado, as칤 como la respuesta correcta.
* Las preguntas deber치n ser respondidas dentro de un tiempo l칤mite.
* Las preguntas seguir치n la misma estructura: 1 pregunta correcta y 3 incorrectas, generadas autom치ticamente.
* Los usuarios podr치n consultar datos sobre sus cuentas, como las veces que han jugado o el n칰mero de preguntas que han acertado o fallado.
* Existir치 un ranking que ordenar치 a los 10 mejores jugadores seg칰n una m칠trica determinada.
* Se podr치 acceder a los servicios de la aplicaci칩n a trav칠s de una API REST


****

=== Atributos de Calidad

[options="header",cols="1,2,2"]
|===
| Prioridad | Objetivo | Descripci칩n
| 1 | Usabilidad | Todos los usuarios deben poder usar la aplicaci칩n sin tener en cuenta sus limitaciones.
| 2 | Rendimiento | Los tiempos entre operaciones han de ser asumibles, aun teniendo varios usuarios usando la aplicaci칩n a la vez.
| 3 | Seguridad |  Los datos sensibles de los usuarios deben estar restringidos al mismo usuario.
| 4 | Mantenibilidad | El c칩digo y documentaci칩n de la aplicaci칩n ha de estar conformado de tal forma que sea factible hacer cambios y ampliaciones en la aplicaci칩n.
| 5 | Portabilidad | La aplicaci칩n web es compatible con los navegadores web m치s utilizados (Chrome, Firefox, Safari, Edge).
|===


=== Stakeholders

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Equipo de Desarrollo | Yago Navajas Gonz치lez +
Zohaib Akhtar Kausar +
Santiago L칩pez Laso  | Los estudiantes que llevar치n a cabo el desarrollo de la aplicaci칩n. Ser치n los encargados de la arquitectura, la documentaci칩n y la codificaci칩n.
| Profesores | Jose Emilio Labra Gayo | Supervisores de los avances y encargados de evaluar la aplicaci칩n final y el desarrollo de la misma.
| Usuario | Jugador de la aplicaci칩n | Personas que puedan interactuar tanto con el registro de usuarios como con el juego en s칤 y completar correctamente una partida.
| HappySw | Empresa responsable | Empresa contratada, cuyo trabajo ser치 el desarrollo del juego de la mano del equipo de desarrollo.
| Wikidata | Proveedor de la informaci칩n de las preguntas | Si la aplicaci칩n tiene 칠xito, para Wikidata es publicidad gratis. Por tanto, le interesa este proyecto.
| RTVE | Empleador | Interesados en la creaci칩n del juego e impulsores de su desarrollo.
|===
