ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
== Introducci칩n y Objetivos 游꾾

El proyecto WIQ 04D es un desarrollo en el marco de la asignatura de Arquitectura del Software, que consiste en la creaci칩n de una aplicaci칩n web similar al estilo de "Saber y Ganar". Este es un juego de preguntas de cultura general que se generan autom치ticamente con la ayuda de Wikidata, una base de conocimientos accesible tanto para humanos como para m치quinas.

Los desarrolladores de la aplicaci칩n son Zohaib Akhtar Kausar, Yago Navajas Gonz치lez y Santiago L칩pez Laso.

=== Requisitos Funcionales

****
* Los usuarios deben iniciar sesi칩n en la p치gina, lo cual permitir치 registrar par치metros como la cantidad de veces que han jugado.
* Se podr치n responder preguntas autogeneradas y se indicar치 si las respuestas son correctas o incorrectas, junto con la respuesta correcta.
* Las preguntas deber치n ser respondidas dentro de un tiempo l칤mite.
* Las preguntas seguir치n la estructura de una pregunta correcta y tres incorrectas, generadas autom치ticamente.
* Los usuarios podr치n consultar datos sobre sus cuentas, como la cantidad de veces que han jugado y el n칰mero de preguntas acertadas o falladas.
* Habr치 un ranking que clasificar치 a los 10 mejores jugadores seg칰n una m칠trica determinada.
* Se podr치 acceder a los servicios de la aplicaci칩n a trav칠s de una API REST.
****

=== Atributos de Calidad

[options="header",cols="1,2,2"]
|===
| Prioridad | Objetivo | Descripci칩n
| 1 | Usabilidad | La aplicaci칩n debe ser accesible y f치cil de usar para todos los usuarios, independientemente de sus limitaciones.
| 2 | Rendimiento | Los tiempos de respuesta deben ser adecuados, incluso con m칰ltiples usuarios accediendo a la aplicaci칩n simult치neamente.
| 3 | Seguridad | Los datos sensibles de los usuarios deben estar protegidos y accesibles 칰nicamente para cada usuario.
| 4 | Mantenibilidad | El c칩digo y la documentaci칩n de la aplicaci칩n deben estar organizados de manera que faciliten futuras modificaciones y ampliaciones.
| 5 | Portabilidad | La aplicaci칩n web debe ser compatible con los navegadores m치s utilizados como Chrome, Firefox, Safari y Edge.
|===

=== Stakeholders

[options="header",cols="1,2,2"]
|===
| Rol/Nombre | Contacto | Expectativas
| Equipo de Desarrollo | Yago Navajas Gonz치lez +
Zohaib Akhtar Kausar +
Santiago L칩pez Laso  | Estudiantes encargados del desarrollo de la aplicaci칩n, incluyendo la arquitectura, la documentaci칩n y la codificaci칩n.
| Profesores | Jose Emilio Labra Gayo | Supervisores de los avances y encargados de evaluar la aplicaci칩n final y su desarrollo.
| Usuarios | Jugadores de la aplicaci칩n | Personas que interactuar치n con el registro de usuarios y el juego, y deber치n ser capaces de completar una partida correctamente.
| HappySw | Empresa responsable | Empresa contratada para colaborar en el desarrollo del juego junto al equipo de desarrollo.
| Wikidata | Proveedor de la informaci칩n para las preguntas | Interesado en el 칠xito de la aplicaci칩n como forma de obtener publicidad gratuita.
| RTVE | Empleador | Interesados en la creaci칩n del juego e impulsores de su desarrollo.
|===
