ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
== Introducci贸n y Objetivos 

El proyecto de WIQ 4D es un proyecto desarrollado en la asignatura Arquitectura del Software. Consiste en la creaci贸n de una aplicaci贸n web al estilo "Saber y Ganar". Es decir, es un juego de preguntas de cultura general generadas de forma automatica con ayuda de Wikidata, la base de conocimiento editada en colaboraci贸n..

Los desarrolladores de la aplicacion son por Zohaib Akhtar Kausar, Yago Navajas Gonz谩lez y Santiago L贸pez Laso. 

=== Requisitos Funcionales

****
* Los usuarios se deber谩n loggearse en la p谩gina; esto servir谩 para tener registro de una serie de par谩metros, como puede ser las veces que se ha jugado. 
* Se podr谩n responder preguntas autogeneradas y se ver谩 si han acertado o fallado, as铆 como la respuesta correcta.
* Las preguntas deber谩n ser respondidas en un tiempo l铆mite.
* Las preguntas seguir谩n la misma estructura: 1 pregunta correcta y 3 incorrectas, generadas autom谩ticamente.
* Los usuarios podr谩n consultar datos sobre su cuentas, como pueden ser las veces que han jugado o el n煤mero de preguntas que han acertado o fallado. 
* Existir谩 un ranking que ordenar谩 a los 10 mejores jugadores en funci贸n de una m茅trica.
* Se podr谩n acceder a los servicios de la aplicaci贸n a traves de una API REST.


****

=== Atributos de Calidad

[options="header",cols="1,2,2"]
|===
| Prioridad | Objetivo | Descripci贸n
| 1 | Usabilidad | Todos los usuarios deben poder usar la aplicaci贸n sin tener en cuenta sus limitaciones.
| 2 | Mantenibilidad | El c贸digo y documentaci贸n de la aplicaci贸n ha de estar conformado de tal forma que sea factible hacer cambios y ampliaciones en la aplicaci贸n.
| 3 | Eficiciencia | Los tiempos entre operaciones han de ser asumibles.
| 4 | Fiabilidad | Los datos usados en la aplicaci贸n deben ser los correctos.
| 5 | Privacidad |  Los datos sensibles de los usuarios deben estar restringidos al mismo usuario.
|===


=== Stakeholders

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Equipo de Desarrollo | Yago Navajas Gonzalez -> UO287746@uniovi.es +
Zohaib Akhtar Kausar -> UO291060@uniovi.es +
Santiago Lopez Laso -> UO277369@uniovi.es | Los estudiantes que llevar谩n a cabo el desarrollo de la aplicaci贸n. Ser谩n los encargados de la arquitectura, la documentaci贸n y la codificaci贸n.
| Profesores | Jose Emilio Labra Gayo | Supervisores de los avances y encargados de evaluar la aplicaci贸n final y el desarrollo de la misma.
| Usuario | Jugador de la aplicaci贸n | Personas que puedan interactuar tanto con el registro de usuarios como con el juego en s铆 y pueda completar correctamente una partida.
| HappySw | Empresa responsable | Empresa contratada, cuyo trabajo sera el desarrollo del juego de la mano del equipo de desarrollo.
| RTVE | Empleador | Interesados en la creaci贸n del juego e impulsores de su desarrollo.
|===
