ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Estrategia de Soluci칩n 游닄

=== Decisiones tecnol칩gicas

* Se usar치 la biblioteca de JavaScript React para facilitar la implementaci칩n de la interfaz.
* Se usar치 una arquitectura basada en microservicios para los diferentes componentes del proyecto como la generaci칩n de preguntas o el registro de usuarios en el sistema.
* Para el alojamiemto de la p치gina web se usar치 una m치quina virtual Azure con el cr칠dito de estudiante proporcionado.
* Se usar치 GitHub Actions para el despliegue del proyecto, pero de forma autom치tica en vez de desplegarlo todo a mano. Cabe a destacar que tambi칠n est치n implementados unos test para asegurar el correcto despliegue del proyecto.
* Se har치n pruebas de usabilidad para comprobar la usabilidad de la aplicaci칩n.
* Se har치n pruebas de carga para comprobar el rendimiento de la aplicaci칩n.

=== Decisiones organizativas

* Este grupo (wiq_es04d) ha sido formado a partir de un grupo ya existente (wiq_es04c) pasando de 5 integrantes a 3. Se ha decidido volver al proyecto inicial cuando se dio la situaci칩n de ruptura del grupo para empezar de 0.

* No existe una divisi칩n clara entre las funcionalidades que desempe침a cada usuario, todos hacen de todo.

* Se realizar치 al menos una reuni칩n a la semana en clase para organizar y llevar recuento del trabajo realizado y que ser치 lo siguiente en lo que se va a trabajar. Se pueden realizar reuniones adicionales fuera de clase.

